on:
  push:
    branches:
      - main

name: Precompile server

jobs:
  precompile:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # TODO: Centralize this data
        target: [x86_64-unknown-linux-gnu]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Verify versions
        run: rustc --version && rustup --version && cargo --version

      - name: Cache build context
        id: cache-cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo

      - name: Precompile for ${{ matrix.target }}
        run: rustup target add ${{ matrix.target }} && cargo build --release --bin orangutan-server --target ${{ matrix.target }}

      - uses: actions/upload-artifact@v4
        with:
          name: orangutan-server-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/orangutan-server
          if-no-files-found: error
