on: [push, pull_request]

name: Test

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # TODO: Centralize this data
        target: [x86_64-unknown-linux-gnu]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          override: true

      - name: Verify versions
        run: rustc --version && rustup --version && cargo --version

      - name: Cache build context
        id: cache-cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo

      - name: Test on ${{ matrix.target }}
        run: cargo test

      # TODO: Only check code style for one target
      - name: Check code style
        run: cargo fmt -- --check
