[package]
name = "orangutan-helpers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biscuit-auth = "4"
lazy_static = "1"
serde_json = "1"
rocket = "0.5"
tracing = "0.1"
