[package]
name = "orangutan-server"
version = "0.4.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21"
chrono = "0.4"
urlencoding = "2"
biscuit-auth = "4"
lazy_static = "1"
orangutan-helpers = { path = "../helpers" }
serde_json = "1"
time = "0.3"
tracing = "0.1"
tracing-subscriber = "0.3"
rocket = "0.5"
