[package]
name = "orangutan-server"
version = "0.4.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = { workspace = true }
chrono = { workspace = true }
urlencoding = { workspace = true }
biscuit-auth = { workspace = true }
lazy_static = { workspace = true }
orangutan-helpers = { path = "../helpers" }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
rocket = { workspace = true }
