@startuml Getting a resource (full sequence)
' skinparam responseMessageBelowArrow true
' autonumber

actor Client
participant "Back-end" as Back
database "Object storage" as S3

!$page = "/page.html"

Client -> Back: ""GET $page""
Back -> S3: ""GET $page"" object

alt Public object exists

	S3 -[#green]-> Back: ""$page""
	Back -[#green]-> Client: ""$page""

else Public object does not exist

	S3 -[#red]-> Back: ""404 Not Found""
	Back -> S3: List ""$page@*"" objects

	alt Private object(s) exist

		S3 -[#green]-> Back: ""["$page@<profile1>",""\n"""$page@<profile2>"]""

		Back -> Back: Read Bearer token

		alt User isn't authenticated
			Back -[#red]-> Client: ""401 Unauthorized""

			group Authentication
				Client -> Back: ""GET /login"" (Basic Auth)
				note right: Shared profile as username
				alt Valid credentials
					Back -> Back: Generate unique Biscuit
					note left: With TTL and\nrevocation mechanism
					Back -[#green]-> Client: Biscuit
					Client -> Client: Store Biscuit in a cookie
				else Invalid credentials
					Back -[#red]-> Client: ""401 Unauthorized""
				end
			end

			Client -> Back: ""GET $page""

			... Restart everything ...
		end

		Back -> Back: Validate Biscuit
		note left: Format, TTL, revocation…

		alt Biscuit is valid

			Back -> Back: Validate Biscuit against authorized profiles

			alt Authorized profile present in Biscuit

				Back -> Back: Read profile from Biscuit
				Back -> Back: Read decryption key from environment
				note left: Key associated to profile

				alt Key found in environment

					Back -> S3: ""GET $page@<profile>""
					S3 -[#green]-> Back: ""$page@<profile>""
					Back -> Back: Decrypt ""$page@<profile>""
					note left: We suppose this never fails
					Back -[#green]-> Client: ""$page""

				else Key not found in environment

					Back -[#red]-> Client: ""500 Internal Server Error""

				end

			else No authorized profile present in Biscuit

				Back -[#red]-> Client: ""404 Not Found""
				note right: Not ""401"" to not leak\nthe existence of this page

			end

		else Biscuit is invalid

			Back -[#red]-> Client: ""401 Unauthorized""

		end

	else Private object does not exist

		S3 -[#green]-> Back: ""[]""
		Back -[#red]-> Client: ""404 Not Found""

	end

end

@enduml
