[workspace]
members = [
    'helpers',
    'orangutan-init',
    'orangutan-preflight',
    'orangutan-refresh-token',
    'orangutan-server',
]
resolver = "2"

[workspace.dependencies]
base64 = "0.22"
chrono = "0.4"
urlencoding = "2"
biscuit-auth = "4"
lazy_static = "1"
serde_json = "1"
thiserror = "1"
time = "0.3"
tracing = "0.1"
tracing-subscriber = "0.3"
rocket = "0.5"
iso8601-duration = "0.2"
